module.exports = (employeemanagerpo, cancelbutton) => {
    employeemanagerpo
            .navigate()
            .click('@employee1')
            .clearValue('@nameEntry')
            .setValue('@nameEntry', cancelbutton.nameEntry)
            .clearValue('@phoneEntry')
            .setValue('@phoneEntry', cancelbutton.phoneEntry)
            .clearValue('@title')
            .setValue('@title', cancelbutton.title)
            .click('@cancel')
    employeemanagerpo.expect.element('@nameEntry').value.to.equal('Bernice Ortiz').before(5000)
    employeemanagerpo.expect.element('@phoneEntry').value.to.equal('4824931093').before(5000)
    employeemanagerpo.expect.element('@title').value.to.equal('CEO').before(5000) 
    
    employeemanagerpo
            .navigate()
            .click('@employee2')
            .clearValue('@nameEntry')
            .setValue('@nameEntry', cancelbutton.nameEntry)
            .clearValue('@phoneEntry')
            .setValue('@phoneEntry', cancelbutton.phoneEntry)
            .clearValue('@title')
            .setValue('@title', cancelbutton.title)
            .click('@cancel')
    employeemanagerpo.expect.element('@nameEntry').value.to.equal('Marnie Barnett').before(5000)
    employeemanagerpo.expect.element('@phoneEntry').value.to.equal('3094812387').before(5000)
    employeemanagerpo.expect.element('@title').value.to.equal('CTO').before(5000) 

    employeemanagerpo
            .navigate()
            .click('@employee3')
            .clearValue('@nameEntry')
            .setValue('@nameEntry', cancelbutton.nameEntry)
            .clearValue('@phoneEntry')
            .setValue('@phoneEntry', cancelbutton.phoneEntry)
            .clearValue('@title')
            .setValue('@title', cancelbutton.title)
            .click('@cancel')
    employeemanagerpo.expect.element('@nameEntry').value.to.equal('Phillip Weaver').before(5000)
    employeemanagerpo.expect.element('@phoneEntry').value.to.equal('7459831843').before(5000)
    employeemanagerpo.expect.element('@title').value.to.equal('Manager').before(5000)

    employeemanagerpo
            .navigate()
            .click('@employee4')
            .clearValue('@nameEntry')
            .setValue('@nameEntry', cancelbutton.nameEntry)
            .clearValue('@phoneEntry')
            .setValue('@phoneEntry', cancelbutton.phoneEntry)
            .clearValue('@title')
            .setValue('@title', cancelbutton.title)
            .click('@cancel')
    employeemanagerpo.expect.element('@nameEntry').value.to.equal('Teresa Osborne').before(5000)
    employeemanagerpo.expect.element('@phoneEntry').value.to.equal('3841238745').before(5000)
    employeemanagerpo.expect.element('@title').value.to.equal('Director of Engineering').before(5000)

    employeemanagerpo
            .navigate()
            .click('@employee5')
            .clearValue('@nameEntry')
            .setValue('@nameEntry', cancelbutton.nameEntry)
            .clearValue('@phoneEntry')
            .setValue('@phoneEntry', cancelbutton.phoneEntry)
            .clearValue('@title')
            .setValue('@title', cancelbutton.title)
            .click('@cancel')
    employeemanagerpo.expect.element('@nameEntry').value.to.equal('Dollie Berry').before(5000)
    employeemanagerpo.expect.element('@phoneEntry').value.to.equal('4873459812').before(5000)
    employeemanagerpo.expect.element('@title').value.to.equal('Front-End Developer').before(5000)

    employeemanagerpo
            .navigate()
            .click('@employee6')
            .clearValue('@nameEntry')
            .setValue('@nameEntry', cancelbutton.nameEntry)
            .clearValue('@phoneEntry')
            .setValue('@phoneEntry', cancelbutton.phoneEntry)
            .clearValue('@title')
            .setValue('@title', cancelbutton.title)
            .click('@cancel')
    employeemanagerpo.expect.element('@nameEntry').value.to.equal('Harriett Williamson').before(5000)
    employeemanagerpo.expect.element('@phoneEntry').value.to.equal('6571249801').before(5000)
    employeemanagerpo.expect.element('@title').value.to.equal('Front-End Developer').before(5000)

    employeemanagerpo
            .navigate()
            .click('@employee7')
            .clearValue('@nameEntry')
            .setValue('@nameEntry', cancelbutton.nameEntry)
            .clearValue('@phoneEntry')
            .setValue('@phoneEntry', cancelbutton.phoneEntry)
            .clearValue('@title')
            .setValue('@title', cancelbutton.title)
            .click('@cancel')
    employeemanagerpo.expect.element('@nameEntry').value.to.equal('Ruby Estrada').before(5000)
    employeemanagerpo.expect.element('@phoneEntry').value.to.equal('5740923478').before(5000)
    employeemanagerpo.expect.element('@title').value.to.equal('Back-End Developer').before(5000)

    employeemanagerpo
            .navigate()
            .click('@employee8')
            .clearValue('@nameEntry')
            .setValue('@nameEntry', cancelbutton.nameEntry)
            .clearValue('@phoneEntry')
            .setValue('@phoneEntry', cancelbutton.phoneEntry)
            .clearValue('@title')
            .setValue('@title', cancelbutton.title)
            .click('@cancel')
    employeemanagerpo.expect.element('@nameEntry').value.to.equal('Lou White').before(5000)
    employeemanagerpo.expect.element('@phoneEntry').value.to.equal('8727813498').before(5000)
    employeemanagerpo.expect.element('@title').value.to.equal('Full-Stack Developer').before(5000)

    employeemanagerpo
            .navigate()
            .click('@employee9')
            .clearValue('@nameEntry')
            .setValue('@nameEntry', cancelbutton.nameEntry)
            .clearValue('@phoneEntry')
            .setValue('@phoneEntry', cancelbutton.phoneEntry)
            .clearValue('@title')
            .setValue('@title', cancelbutton.title)
            .click('@cancel')
    employeemanagerpo.expect.element('@nameEntry').value.to.equal('Eve Sparks').before(5000)
    employeemanagerpo.expect.element('@phoneEntry').value.to.equal('8734567810').before(5000)
    employeemanagerpo.expect.element('@title').value.to.equal('Product Manager').before(5000)

    employeemanagerpo
            .navigate()
            .click('@employee10')
            .clearValue('@nameEntry')
            .setValue('@nameEntry', cancelbutton.nameEntry)
            .clearValue('@phoneEntry')
            .setValue('@phoneEntry', cancelbutton.phoneEntry)
            .clearValue('@title')
            .setValue('@title', cancelbutton.title)
            .click('@cancel')
    employeemanagerpo.expect.element('@nameEntry').value.to.equal('Lois Brewer').before(5000)
    employeemanagerpo.expect.element('@phoneEntry').value.to.equal('8749823456').before(5000)
    employeemanagerpo.expect.element('@title').value.to.equal('Sales Manager').before(5000)

} 

        