module.exports = (employeemanagerpo, savebutton) => {
    employeemanagerpo
            .navigate()
            .click('@employee1')
            .clearValue('@nameEntry')
            .setValue('@nameEntry', savebutton.nameEntry)
            .clearValue('@phoneEntry')
            .setValue('@phoneEntry', savebutton.phoneEntry)
            .clearValue('@title')
            .setValue('@title', savebutton.title)
            .click('@save')
    employeemanagerpo.expect.element('@nameEntry').value.to.equal('Bern Smith').before(5000)
    employeemanagerpo.expect.element('@phoneEntry').value.to.equal('6098510187').before(5000)
    employeemanagerpo.expect.element('@title').value.to.equal('CEF').before(5000) 
    
    employeemanagerpo   
            .navigate()
            .click('@employee2')
            .clearValue('@nameEntry')
            .setValue('@nameEntry', savebutton.nameEntry)
            .clearValue('@phoneEntry')
            .setValue('@phoneEntry', savebutton.phoneEntry)
            .clearValue('@title')
            .setValue('@title', savebutton.title)
            .click('@save')
    employeemanagerpo.expect.element('@nameEntry').value.to.equal('Bern Smith').before(5000)
    employeemanagerpo.expect.element('@phoneEntry').value.to.equal('6098510187').before(5000)
    employeemanagerpo.expect.element('@title').value.to.equal('CEF').before(5000)

    employeemanagerpo   
    .navigate()
    .click('@employee3')
    .clearValue('@nameEntry')
    .setValue('@nameEntry', savebutton.nameEntry)
    .clearValue('@phoneEntry')
    .setValue('@phoneEntry', savebutton.phoneEntry)
    .clearValue('@title')
    .setValue('@title', savebutton.title)
    .click('@save')
    employeemanagerpo.expect.element('@nameEntry').value.to.equal('Bern Smith').before(5000)
    employeemanagerpo.expect.element('@phoneEntry').value.to.equal('6098510187').before(5000)
    employeemanagerpo.expect.element('@title').value.to.equal('CEF').before(5000)

employeemanagerpo   
    .navigate()
    .click('@employee4')
    .clearValue('@nameEntry')
    .setValue('@nameEntry', savebutton.nameEntry)
    .clearValue('@phoneEntry')
    .setValue('@phoneEntry', savebutton.phoneEntry)
    .clearValue('@title')
    .setValue('@title', savebutton.title)
    .click('@save')
employeemanagerpo.expect.element('@nameEntry').value.to.equal('Bern Smith').before(5000)
employeemanagerpo.expect.element('@phoneEntry').value.to.equal('6098510187').before(5000)
employeemanagerpo.expect.element('@title').value.to.equal('CEF').before(5000)

employeemanagerpo   
    .navigate()
    .click('@employee5')
    .clearValue('@nameEntry')
    .setValue('@nameEntry', savebutton.nameEntry)
    .clearValue('@phoneEntry')
    .setValue('@phoneEntry', savebutton.phoneEntry)
    .clearValue('@title')
    .setValue('@title', savebutton.title)
    .click('@save')
employeemanagerpo.expect.element('@nameEntry').value.to.equal('Bern Smith').before(5000)
employeemanagerpo.expect.element('@phoneEntry').value.to.equal('6098510187').before(5000)
employeemanagerpo.expect.element('@title').value.to.equal('CEF').before(5000)

employeemanagerpo   
    .navigate()
    .click('@employee6')
    .clearValue('@nameEntry')
    .setValue('@nameEntry', savebutton.nameEntry)
    .clearValue('@phoneEntry')
    .setValue('@phoneEntry', savebutton.phoneEntry)
    .clearValue('@title')
    .setValue('@title', savebutton.title)
    .click('@save')
employeemanagerpo.expect.element('@nameEntry').value.to.equal('Bern Smith').before(5000)
employeemanagerpo.expect.element('@phoneEntry').value.to.equal('6098510187').before(5000)
employeemanagerpo.expect.element('@title').value.to.equal('CEF').before(5000)

employeemanagerpo   
    .navigate()
    .click('@employee7')
    .clearValue('@nameEntry')
    .setValue('@nameEntry', savebutton.nameEntry)
    .clearValue('@phoneEntry')
    .setValue('@phoneEntry', savebutton.phoneEntry)
    .clearValue('@title')
    .setValue('@title', savebutton.title)
    .click('@save')
employeemanagerpo.expect.element('@nameEntry').value.to.equal('Bern Smith').before(5000)
employeemanagerpo.expect.element('@phoneEntry').value.to.equal('6098510187').before(5000)
employeemanagerpo.expect.element('@title').value.to.equal('CEF').before(5000)

employeemanagerpo   
    .navigate()
    .click('@employee8')
    .clearValue('@nameEntry')
    .setValue('@nameEntry', savebutton.nameEntry)
    .clearValue('@phoneEntry')
    .setValue('@phoneEntry', savebutton.phoneEntry)
    .clearValue('@title')
    .setValue('@title', savebutton.title)
    .click('@save')
employeemanagerpo.expect.element('@nameEntry').value.to.equal('Bern Smith').before(5000)
employeemanagerpo.expect.element('@phoneEntry').value.to.equal('6098510187').before(5000)
employeemanagerpo.expect.element('@title').value.to.equal('CEF').before(5000)

employeemanagerpo   
    .navigate()
    .click('@employee9')
    .clearValue('@nameEntry')
    .setValue('@nameEntry', savebutton.nameEntry)
    .clearValue('@phoneEntry')
    .setValue('@phoneEntry', savebutton.phoneEntry)
    .clearValue('@title')
    .setValue('@title', savebutton.title)
    .click('@save')
employeemanagerpo.expect.element('@nameEntry').value.to.equal('Bern Smith').before(5000)
employeemanagerpo.expect.element('@phoneEntry').value.to.equal('6098510187').before(5000)
employeemanagerpo.expect.element('@title').value.to.equal('CEF').before(5000)

employeemanagerpo   
    .navigate()
    .click('@employee10')
    .clearValue('@nameEntry')
    .setValue('@nameEntry', savebutton.nameEntry)
    .clearValue('@phoneEntry')
    .setValue('@phoneEntry', savebutton.phoneEntry)
    .clearValue('@title')
    .setValue('@title', savebutton.title)
    .click('@save')
employeemanagerpo.expect.element('@nameEntry').value.to.equal('Bern Smith').before(5000)
employeemanagerpo.expect.element('@phoneEntry').value.to.equal('6098510187').before(5000)
employeemanagerpo.expect.element('@title').value.to.equal('CEF').before(5000)

}

        